/**
 * OpenAPI description of the endpoints that are implemented today. Add a path
 * here in the same change that adds its route; tests/integration/openapi.test.ts
 * checks that documented routes respond.
 */
const errorSchema = {
  type: 'object',
  required: ['error'],
  properties: {
    error: {
      type: 'object',
      required: ['code', 'message', 'requestId'],
      properties: {
        code: { type: 'string', example: 'VALIDATION_FAILED' },
        message: { type: 'string' },
        requestId: { type: 'string' },
        details: {},
      },
    },
  },
} as const;

export function buildOpenApiDocument(version: string) {
  return {
    openapi: '3.1.0',
    info: {
      title: 'MiNi Payment API (sandbox)',
      version,
      description: 'Sandbox/demo payment platform. No real money movement, banking, UPI or card processing is performed.',
    },
    servers: [{ url: '/api/v1' }],
    components: {
      schemas: { Error: errorSchema },
      headers: {
        RequestId: { description: 'Correlation id echoed or generated by the server.', schema: { type: 'string' } },
      },
    },
    paths: {
      '/health': {
        get: {
          summary: 'Liveness: the process is running',
          tags: ['health'],
          responses: {
            '200': {
              description: 'Process is alive',
              headers: { 'x-request-id': { $ref: '#/components/headers/RequestId' } },
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      data: {
                        type: 'object',
                        properties: {
                          status: { const: 'ok' },
                          service: { type: 'string' },
                          version: { type: 'string' },
                          environment: { type: 'string' },
                          providerMode: { const: 'sandbox' },
                          uptimeSeconds: { type: 'integer' },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      '/health/ready': {
        get: {
          summary: 'Readiness: MongoDB and Redis are reachable',
          tags: ['health'],
          responses: {
            '200': { description: 'All dependencies are up' },
            '503': { description: 'At least one dependency is down; per-dependency status is returned' },
          },
        },
      },
      '/openapi.json': {
        get: { summary: 'This document', tags: ['meta'], responses: { '200': { description: 'OpenAPI document' } } },
      },
    },
  };
}
